version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm install; node ./test/test.js
      - run:
          name: Trigger docker remotely
          command: $DT3
test:
  override:    
    - mocha

