version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: echo 'hello world'
      - run: npm install
      - run: node ./test/test.js
test:
  override:    
    - mocha

